kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:Y9hH8xv39y5F5DnC8Oz6hYuwGb/ELtvVNBqaDRFON267A8a46r8ii9T9WHOm,iv:Lh0nHL+6nY9IOV+phbeluo/fRRGV1AOui+ALu/A6E00=,tag:Ugazsy7B1ssKSCVdVIzJ+g==,type:str]
    github_user: ENC[AES256_GCM,data:i6oNIaZ3,iv:XpECV88y0dI8WXIBUucebxigtQfMt2zxt0P2NABOgtE=,tag:ELBJXnEEPMhhq/tC4KisfA==,type:str]
    github_api_token: ENC[AES256_GCM,data:SV0dz/WceE/FzDH3PnSLl0MDntU+zhbFtYQq1YpnVLIu3auk7ZPPag==,iv:79msEBa2Qc+AzvakN9mWQdNpn1+VJiOJcKJPSukn6B0=,tag:Ih3vV49xhoa66qXBvVkZUw==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:enZeJAnCTKo=,iv:kal8QsSnyLyrf7k/ox6MJMfTE/k4Zm8M4wqlZPzuxu8=,tag:DfwHZ2/bo8KP5n8k9E9Y8w==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:dgdjiJxF/kJnyaq/a+BO6iVD+2f7luuc/L5OPOLEZNyASKNd,iv:cWAcXBEImNUiHA8SYAVKEjIXv4GOhfuUpWKybLAf5/Y=,tag:SutKTLHFPXwu495LqVzKbA==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:t2TbWZwe3wRIRFK8,iv:L7fhNCxq3uy6GrSnejbL4EF0XckwG4XfVa04aKh9fGc=,tag:G1vmZBJ8LB+nLFID8RH2eg==,type:str]
    prism_central_user: ENC[AES256_GCM,data:NC3S4sI=,iv:5N2PpJe5zTcN4X5qiqf5Kqpf9E9wVeXk8QRbJmFx2cE=,tag:UkUE6+UWGRWpXGT3wsC8BQ==,type:str]
    prism_central_password: ENC[AES256_GCM,data:OpIufBN6VmG2,iv:1EFJK0EK+sGdPTgS5BdbavzSYQ/Qwme4Zi13+re1kug=,tag:brafa8NWnpQzRePM6TTTXA==,type:str]
    objects_host: ENC[AES256_GCM,data:7nZw05v1mDE5eN3H,iv:Z3PHn3l6X/LB2W/lOER3PVfd9GGsBqXDZiU+7plKhh8=,tag:LhuWzIFKSbeaPPWW96ZBug==,type:str]
    objects_port: ENC[AES256_GCM,data:I+k=,iv:GcwDiqSFWFNzFj2q3pQ1UYMgnBV9wBS9BZW4O/I6adY=,tag:TUKS5RcBkX8nUJP+SVfM8A==,type:str]
    objects_region: ENC[AES256_GCM,data:ybqpcQLzMETV,iv:KGNAkyLzw7MZTkbWaCUmIFnyRpXVFAaxQfftyAaVShE=,tag:FmzTKrTrvIrcCgrAFK0TTA==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:O/wSMn0=,iv:BMkv5xfff2bO97obGL+NffNnOCzcRaUOvSr3ML+EULM=,tag:4oblE+cnoBG4EN84ygYeqg==,type:str]
    objects_access_key: ENC[AES256_GCM,data:umMlwzPl8BLOKJt7moKcvW8cwh5bAz+eDRRJQGmjlCE=,iv:Ny5+Ot7skzUlEc6XRzgG/qkm3+6RDRW9lI98yyaVSEY=,tag:2kJeH9HO9nxE7CA//C0mAg==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:Oma0JqW52q6Y0fbr6pEMCE4kekW0r0PcOY0QFkyljBE=,iv:meApWeC/d0i9H4Ysmzm6crPMAemGnjR3YLX6r8T1DZ4=,tag:t7eieW/V8dxVr/Or86owVg==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:00pldLATz/qqjGapiUD5GaPRvqPwuWNqfQ==,iv:yvWhIvrXFSyHW2kLtGsj05XT6X5p71UQnugTg7dPo60=,tag:a7KTCJrSA9VKS6ENU3SVTQ==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:9/UpiiiDtL/pSmAEKc2a,iv:SZgy+9w7Ao/rQUvFTXU8+rHnNQR/V66icCxz8uxqEkc=,tag:1/LJ5TAFudJ5SEZchET9ig==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:zqs1NByM3k3c3CQcZGcgsQ0v3JLWQiM=,iv:MBGVNOK/tDFjlsAc3cMUJPaoF0i/ljm7OCSmMdDhtYM=,tag:oPaai+l2Jpa3fbZLbbn4YQ==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:ZY9r2izu1a3QVWFMWqR5ujrV0VDvjyw=,iv:htR478U57ka3iaUVc9NU9wVgY45WKJKF1+lOeVN7n+g=,tag:Hg28TdEmF953zWIKs0hv7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17m5tuavf9aam25cdguwmv3qfywyt9wclvwwfvqaeads02t4py3cqxfz686
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5S0c1ak5wR0RqdmgzOEpB
            R0xKN0tmRVFQQS9PUXdQZDdobFlzU1BGMGhRCml5WlpJVVR5OExZUlJydGFxOXI2
            VEhoUkhUWUVEWWVyMEFRMDAxdzdzRlUKLS0tIGU1ZWg1bG14RDFvZXFDMWVsTGtI
            QjM4WmxwMCt6ZE1YR29kSGhTYlhRT1kKaMOTK9izBJRNM0h/cF4iZFuvsjpmoU7a
            DT8xQjOtlEXKLhxLhb+b8aM8PKa4qXxWXQqxppP0NAmt4HRjhkK56Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-13T04:11:00Z"
    mac: ENC[AES256_GCM,data:f1x/VtH8Rmw+6kqXq0ua4zwdaBMzGZZIpBwAYf/PZXssyERv/9Pt7oR6dhhXNvlZPxmGwAIfov3sk2e98MpFcTc2IFrWC9Qj9WBM1oEhMnWQVpKsGp0OxWQBVLt9I3lWXidBCTQBi/cOn7cb3+i+NXHReseaAs8T20AUXkeaMX4=,iv:oR+EqdX6Hmqwh3h6vhZGPTAaFxnedWRgGEOvlqDl6xQ=,tag:82dEakQ4PHaIa2Z/czqq0A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
