kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:9Rs09jY0gNoWnhtv6SwLOI4WOue6zQN0ufcrfP6w91dLkRUGadfs5d8r+hW2,iv:L1AKLPn3isPMZvakDHxqKlFZXmVOmYwOQQEKOTnDI/Y=,tag:y2PBJ31++wKUhN0j1l5zzw==,type:str]
    github_user: ENC[AES256_GCM,data:1t/FR2Qx,iv:c5x87WkKS3dq6iTMWkbfSfB72lDOjyYk+BUCFe3r810=,tag:Ydb+SNkKmOl8Ry5v1PBjsw==,type:str]
    github_api_token: ENC[AES256_GCM,data:dElxmY4LzLRG1QS6C0JgF8a/GHBTyX/uljzHrkuIMAycPOsQXUCyiA==,iv:Dkictbaoiq/z4vTlmA7n77UEjlBymvOLhTaGJrPvm28=,tag:9q44k774AZzC+eShuxE2HA==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:uAnYvUoTcC4=,iv:7bH4dZuXcsneJf+u9x8RP6lVVWo/ORFFpSS+lKqm5uo=,tag:/vXHKfqD+etWfVlN3b6G/w==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:GvFkDhOse+e7tyDnNzbFjs6zs8n2daN6NSdIAzh4lbBtKwKz,iv:CD5+ru1/WuspHYw8PwuNABH9IC+2qcNvSBNfZ0XuanA=,tag:uyJoqFj9x8BSGt9a+4aYdA==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:XOvUvsssWnfrFoo5,iv:3UfOfOBbnYaW6VMK6J475gKrRN5MAuVWPS6mAqK897E=,tag:j64eyDiYGO7pL2fMSBywyQ==,type:str]
    prism_central_user: ENC[AES256_GCM,data:XMmpfxU=,iv:lWfLPy3dpobPLSRPJa8fo+FcYGeKOSv38oPzCJFYRV8=,tag:IZ344SQyWp83F1PyQPcgMQ==,type:str]
    prism_central_password: ENC[AES256_GCM,data:T3I3k9w6YNwC,iv:7kG0V/Q64tZY4qcfw91q0XVa8Q2S/FbcxWxF3PbdZnE=,tag:39rYFurwxdbXnWjKKZ0nLQ==,type:str]
    objects_host: ENC[AES256_GCM,data:IsT4fd50/g6ineFk,iv:so3W3wXx9x7qEn+p1XIP393CCBoc+Y977VZnQSlBRvs=,tag:O1p7aQfl41xBtE3bJgA6Xg==,type:str]
    objects_port: ENC[AES256_GCM,data:im4=,iv:WXmuNaJ1kmC0vkA3TEYSiaOuw64Bwf31vwfNX9dmdg4=,tag:Iaf04NFxiyobrw5SQ4CbLA==,type:str]
    objects_region: ENC[AES256_GCM,data:Wzao1M9DlaqM,iv:SZWBfGsOSW+wDuZ95vILUWCLCT1oC9BLiJBsuWJv7lU=,tag:0o9vzwvTbuD9ahiD0quFhg==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:C+ubxYg=,iv:gUCRvevOzoKQtz7BP3U14vXp4JET1HZWka1uKtd5UaM=,tag:8/xR+6WKG20TbE5UdPGZdw==,type:str]
    objects_access_key: ENC[AES256_GCM,data:89gcLo97A3Oz/3+xqmXmzJYCMthAfGYdpTqiTd4mM3M=,iv:HgyO+JSMncdkbeqWsELMOQVDrUYmhSTfzkHxzx5LF+Q=,tag:gbHt1GqxakAW09gEGzMAKQ==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:PS07YN9qPdc3wM71yZrGAS2VZo2DC2JyRb8SmFJznUQ=,iv:dL4a6GFxEjT4VVMzyl9q+89UD1z3ZBD/BFBhhqqMN8M=,tag:aeEdRUNV8TjBzN+RUNCKvg==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:eIj7+2cyiGyzf1Jj8nKnRKQ0cuWGxp2Yzw==,iv:SsFz4TYzPB/GHlvy6ZO/8d2E6aqOvMWOvW8YnrWe4/I=,tag:A67/OZhurBmgNN9VkNuVSQ==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:1s+qv6Kpxr2LtAGdL9Lq,iv:2oMhmygOZCPw24bi4FUpe9K9R4eXrDJ3vvfBd/pGCvg=,tag:9XCzK1h8mMpM2gCu7OvPWg==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:UdPrbt85+ctm/rWzWEjSUMZ26gBr+Ls=,iv:lwasLsKCX4R13vgWAhQAKvDn5/j1wMpJfrmIGJf2ZKY=,tag:MyhfXvjfZmJDw5+PvfcfOg==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:ffAha620w6eQvuEsiFRqnrExtAmaLmQ=,iv:+EUR9fXA95aAUcg4dTTIlwGB3FeJdZAwLf23tZv1+Cs=,tag:1zkl9685e5cH/WOuv0AQNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17m5tuavf9aam25cdguwmv3qfywyt9wclvwwfvqaeads02t4py3cqxfz686
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMndLN3RRZmE4YzRwVHU0
            VWtNdlduSU5vYW9LQlVOc2EyWnIrSUl4RDJRCitsb3A3SkV4N0VpOEs2NnQxai9w
            NmZUdUhFOTRzL1kwU2FjVk1NTjhObjgKLS0tIHI5a091RnNjZTRTYnQ0R3hDVFBU
            c3ZSb1F1UTBaaHdhNElOY2ovOGxTZ2sKGzWNHqIlQdWUu1Nt7yXFjdHrtZ7XhFLW
            pao2JWdsgF8N1t2yqs0k4sfhDt3OuopeRRXk+B/YDZdMLvoWZjAAeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-10T20:42:39Z"
    mac: ENC[AES256_GCM,data:tdANmXZMcRKk99DFwMcIO3vTC/LbSYjC8317dlOkWOiXZRppIDv4kfFmRyQBKWLGr3UXPWH8c4Rj1LHau88gqrgmD70TmPLNzMP+OVw96yznsT5TpdIkC85mQV7q1mqTy1Rk6SY3DVikn4W+6+8sAbdkrcWq3OLQofGwecPu07Q=,iv:ZkF7SZfI3jX59fFFzK41F9v5p1nM1Q8mTs6EKij1yf0=,tag:zUFpN8gt2FUzunUqVT/2bQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
