kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:l0P55p8YgFWfRcpZAN64jqWzE6gTut65va28tGIOMLATXGnSRNXZ2+syvCgh,iv:pmvpvE4qVh8nItgY7Oo4hU8O+90WwcYCUYP1vDAoy+A=,tag:Lj2wvAs3CzxIJVNTmzkAWg==,type:str]
    github_user: ENC[AES256_GCM,data:pVCkJKzt,iv:Wwgkq0mw0PCssgxfJZ2SIz5Mm9q2lX+oMvxe31S/sQM=,tag:fFwAJaNWaCWCJugORWOtmQ==,type:str]
    github_api_token: ENC[AES256_GCM,data:ZItmf0Edvnk19qJsGem265LVpgJAozUfKRaQSju/d19QWcQueox9Hg==,iv:aDKMRbGh63JLTkt2VaY2RcbOLveHD5kv+Oi6JJuRZD8=,tag:1yfsa+sfF2b9CYokTZ88dQ==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:Z1vtMiczvFk=,iv:FEmaDiA4sR0fEVGrjcjPu9syoXJTiAcJodcYwhhjMRs=,tag:nF1n4iX51WthulS6CwKIiw==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:jzn1GW8cKdN1bxL/LFt5U3PPP0MuNuSH2rRZi4KHFK+xtcaS,iv:1U6xHwXAks5gO9vM1/tENIsx31Aoqn6l578g9sNjJx0=,tag:QcDwZ5BUYpifGVFUPByh7Q==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:u/BTGp59FzMuz2z1,iv:r3e1/3mctXhG0j5PSPCnc6Z/DUXV14W+w30rzHHQTbo=,tag:Xc5xhHO5FDQCBa+d4neXHA==,type:str]
    prism_central_user: ENC[AES256_GCM,data:cc/Wapg=,iv:fSZu1IuJB4Epm/cJeCdHAVBJrhpf+4Bkc6w1br8w0Ro=,tag:xrbWAq8KHNeim+yCsFojEA==,type:str]
    prism_central_password: ENC[AES256_GCM,data:fiFqVha18h4iqg==,iv:MZuHhxjLX3BPCDbf70VbgJDsNPhBIIb9QeWGGvxa9vg=,tag:scLY1Yibzo6T5qPlCpy2bg==,type:str]
    objects_host: ENC[AES256_GCM,data:fTSYEtzZkOVbye3G,iv:qBWA6yAwEeVS8PidHYVecZr/7fqql9qa5qF095axVJQ=,tag:m0B9JNdNP2nT7ur1FJ+oJA==,type:str]
    objects_port: ENC[AES256_GCM,data:U+w=,iv:xaZVbijWFRs8gEcqPbwYByZ8VGq5gKjnYfPRUMQ4A/I=,tag:u0ABGcXQdaoQU6tICl1nBA==,type:str]
    objects_region: ENC[AES256_GCM,data:5Docho/yDaiF,iv:XbFda50rVhS4XveHpwa0P6dvmDpXu02NYuHuBNz5x+E=,tag:DkNuw7EiU43bz0ej+poxPw==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:aYxlRdA=,iv:Nph5/beFhCeOAY9lKfSnQRHmVb3ACXyE9FuSwjX384s=,tag:EZD+O/IANcBpE4hqV51elQ==,type:str]
    objects_access_key: ENC[AES256_GCM,data:sEfiUjiFDp0uTBnvwSRPPyVy+D7yCEbg1Yg/Ee6ZJws=,iv:gGWngdvxdCUFrduQ12DN4A/4tg9upD3o+9WaEyRqfb4=,tag:IHHaWKeIGrt+/GZWfFNe1g==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:IP34zwKVMKSOKxCQN8q1DG0oHAIbmVVN9a5T7IvUe2E=,iv:+u6z9FnO1NlBHJ7721VG7P77ahKXkbVp+QsJE9sqLSc=,tag:wKRML9EOV9F12BgxKnkYkw==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:yIPVOBrSFiuJyaStN9VbLXOqT59QjkLkPQ==,iv:lAtvQ45Ub5lZZxqBKtctecoaNOvWPLP9NBVjc/5wItM=,tag:DFs7wMssUiUEzW4naDYbXA==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:3WUtWESgWszQAHBMVVHX,iv:ZuGgq30lW+qAKOTN2ZYymUF6YtRqMobT1GqWv53YpWQ=,tag:R3GmVUYLMxbvJ069Xknb8w==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:ILxDq4h2kft8IURAIq3dlBGEpcx/TjA=,iv:KOCKBJUPvWV92kEC8d/KIj1dG5T801OzstgE3RUXboI=,tag:B72Dup29PuH9AJqZ31tqCw==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:KRXQhljZ8m7ZtRDgN5C6c8iRmh0gdlg=,iv:NSV9irn3YojI1Qn239MT6o6b5IlLXwiUP/uYbLpI25Y=,tag:dF6hVQo53YdCVqrIiWbfMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u7nt62nsaxggpjh8mmpfanqgdptnscqrkd4n03qxraay7lt62fhsf64fse
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzR1drREoyaEVueFdDb0th
            ZEF3b1FKTHhBb0luLzBYandmbVFMM2hVQVdjCmc3RFMyVmVRV0JWYmYvR1hOYkor
            YmlxSWJXaFBMN09sYnJzclFPNXA1SjQKLS0tIE83R283Q1Y2SmlKeS9SQ0ZCTlY0
            OXlsblZCMkorL1dTcGZWcGJmOEFkWmsKiMxTg1BkbGsczIVXWQVP+1Obab7ABoub
            Z7xGe4cYWL1eqEon7+Hl/nGz6+lb/fvlVkWecLJ+TY3eWI4nP0bhqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-19T13:16:49Z"
    mac: ENC[AES256_GCM,data:lyogzHfmUBgONDziyWKwJoCK06O2iiQf2wDvD09ez3RDVOxhArIj34EdTrtc++ZPFbc+BiSzXUx5lVGJO8dpuShz01Eo6ZV0t7N4L/VZ0w1eFnltaqFMk8PFcIq1Weay6TAPoBpbVQjm39qu7jDeA/WmJZYZ58aDLN5pdzupBW0=,iv:kJ9hAUGlww0NKGuJ7kskQ0h2gGej+j82DlE4lwr+xmY=,tag:LR8CSXe1/IJ/f348T1VAHA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
