kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:geiwKKhn4QgrugIu3AipNYxdzxyoSx9w9yXqoFEvVY3M4PI40a+mw/c9mDD+,iv:OTsztCkVRB+edqFJt/dyQpyhRwcT1M3ZoWXLzorfFKE=,tag:9GgtQXWQHNN+9H+ZKtJjAQ==,type:str]
    github_user: ENC[AES256_GCM,data:zQQ19HLF,iv:e9nD0RPMgYJHmHpwffdUjqoBKVsfPvR+9o14qAIoXmk=,tag:kKD7sltjhPrg7IW3eGiktA==,type:str]
    github_api_token: ENC[AES256_GCM,data:kgbmh+OG2SIkOxswmaKpyCXFkFNKQy2qY7T10dTXIK8Jqc8ntV33YQ==,iv:9Vc+BDY6FdQO7vHA9F0RhWEMEN5PmQuGMMaGUmOCaPU=,tag:Pbk6JZAvt8ntpmyomFUl+A==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:jQHO4usXmko=,iv:gRHHRxsG8HVDaH1TD7MJd2Iu/LWRquZu0i7i2Qp8c9A=,tag:7DKKudUkF/WTYKGQ1Q5rXA==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:aP6rj+lwkCH0N93PKphWg4/e4Ya+cI8fBzK6OpMrFrgASLCj,iv:0AR1qmr+xn8Euw3nSRFy9p0+V2GdYYlBlwQcFb5h+Hs=,tag:gYFxXZT6mcRYvzQ77Y0czg==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:36gJTSIDo9j1Bf8M,iv:6saTMXtELKr2vkpSqXihZpJ2WoAyz0zEInXXN3MURXs=,tag:KhOUeMU2wmkVPsqA3lKWSg==,type:str]
    prism_central_user: ENC[AES256_GCM,data:NS1R3hg=,iv:CsmpDRDJUG4jpcLBzR7Z1GJxVmISWgZyaMZ4SbAuvNM=,tag:0N2YWB7kC9Ikgp3X4VsOkA==,type:str]
    prism_central_password: ENC[AES256_GCM,data:jnhxNUAOx0+s,iv:jxmiij+brRyhrCO5qw74XNrVyjAfvMetKmnnaVCrpIk=,tag:ve7M3c0X3rxBfLr+EzysDA==,type:str]
    objects_host: ENC[AES256_GCM,data:WmFwBRrhwkh7rlaA,iv:w+75NPhbM6Sm5oxdVRije6WNrTJZOWA8yM0+BcxwEaM=,tag:6Wo0BU2SGjcxcOs7MVLrvg==,type:str]
    objects_port: ENC[AES256_GCM,data:/U8=,iv:eNUJoe/+fSJGbDbtvB1CqjpSl+spRfxTZNHnKKYVx0w=,tag:Q8NYwuHN3rdWYtIp5NOE2Q==,type:str]
    objects_region: ENC[AES256_GCM,data:Fen0em4HL32s,iv:I8yX6I9FYFsoV5+PyC/mF1FffwpwlqMMs8g4nWyeGz4=,tag:OuCeYke5E9PBNkYHrXzwNQ==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:vTd7z8E=,iv:YHpjFlqRBMJm155bfisBwy+r6L3RygIBupVgCTedgsk=,tag:C3f8Tuiej+0KIp8UiAZhaA==,type:str]
    objects_access_key: ENC[AES256_GCM,data:+Xzw6NcKLIkv5Z0ZOQ1Do8Zh7op+BfB2xI8nxc7z0hU=,iv:EXflyRXHXSk1JtB9pqmToud2HjcbSZ/FWIX7r+c9J7o=,tag:cf12p82bFV9x8sA3GEwKAw==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:wvAkf9uWNN4rBJiMFWmsm1DRNrQLpvWXgq1zGqNQIDM=,iv:rAu2pcQNYVOgqDFy3eyb4NyczYBVumAo5YNoz5gt/Ik=,tag:JU9DH+fCHSTE1ewhChAF1w==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:BobKFtR+2Gru5C8quJzBmA55FmWLEC8ptw==,iv:PtIUI6rcZcw+mmcfhbYWZFeopMFc+2uEYnm1d5HDUwk=,tag:i02bJoSB5ok/AojI4PAUzQ==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:bAMfUeCdcGLAbV27hUJz,iv:eYmC1wQf7xytCRij8blprVLzgnMF8JnilTjhoM+sP4U=,tag:6ozyihW1dhNWtwwpUUC6yA==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:jkxV3X/Nwwd10U9AhnTBrPfZWIpaUJk=,iv:mqWWCrz68hP6gUkiY4B4YXr8z81YXKdtNrkiQyBIF1g=,tag:ZZ03QpoNg2yNv5mUJoVkBQ==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:1SYgMcqZJDublVlGfNX9QDwL+7RQBwM=,iv:cnutswZrbpTx6pnN5q0hHqTKxNJqKWsT43NtMAPwovs=,tag:snzDpVHYdj2dUi1Z91XqfA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17m5tuavf9aam25cdguwmv3qfywyt9wclvwwfvqaeads02t4py3cqxfz686
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UVJnTHFqL0x4MjVDZXNz
            bnJTdjhrMlUyeGVteTRqY1AyNGxZK2VEWXhjCnBmYWcxUXIxcU9pS3lBSzFrNDFC
            S3ZoN2VWRGg5V1Z0c2NGYWJOQ0VZc3MKLS0tIEJOUFdpdnpoTCtzQTJrZ2k4d2Qw
            RE5NQUJGa3g4VEUvVjI4R0RhbE0vMjgKYbUxGBDrpBPdZ9H26GIbSRBgQBP9RgVd
            OSQE40H3ayCYlofKuhjLEFnms/tvSwxjXTlRyPp+2r5k6Z+AAzzMkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-17T05:43:47Z"
    mac: ENC[AES256_GCM,data:V7JeceE8piWn9ogNF5wmtDf2XBsegZOAiiJr8a5kTlwRikBEDt1HVQEa7vi6gF3y41m5Dvfheb0ntTwTRnGDyHIAHaNKKWnUg2EtTqFSGSzj8zku+K3V4x+kHYGvnFZPREYtiFCpVDcMtyO+oXzDaTNHXk+Q8fRlPtMovZQtbGs=,iv:fSrZAiEZWL0ZebURfgoWImTJ2W+sxJZs2GAlA7ltsAU=,tag:Kz9S2l8TsbmAdw/qCBdP3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
