apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nai-helm
  namespace: flux-system
spec:
  dependsOn:
  - name: kserve-post-deploy
  - name: gpu-operator
  interval: 15m
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/nai-helm/_base
  prune: true
  wait: false
  healthChecks:
  - apiVersion: serving.kserve.io/v1beta1
    kind: InferenceService
    name: llm-llm
    namespace: llm
  timeout: 15m
  postBuild:
    substitute:
      namespace_name: llm
    substituteFrom:
    - kind: ConfigMap
      name: cluster-configs
      optional: false
    - kind: Secret
      name: cluster-secrets
      optional: false
