kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:Yn8sr4pl/d3Ym5s59tcrPr4/5yk+U5YCZOOcdA/sLf2KTi5KBZWkLy68DFHN,iv:i1yPD6STQPcuF22FlrIykGIW9FTtaQWdA1vMY56HlOo=,tag:1lcx/bpKBHTXqVhmSayWow==,type:str]
    github_user: ENC[AES256_GCM,data:/S5qC23f,iv:7Uf36dzjRKXREvWRxS3TFIRgSUiIw73bRXWYMVHm6pc=,tag:WqSE3Zpm47L6GU0hG0VKuQ==,type:str]
    github_api_token: ENC[AES256_GCM,data:S8bhn0ZkWKyPSGV/GYXiyF69FvobiBiryD9U56FBEwuTN0AKzCOPlQ==,iv:jrujWS2baxO9SFPkhxSh2NUjS+hvmu1otJZQXJ15puo=,tag:1Bx/ts3HE2UIwnY358Obyg==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:ecjq1aWDFGQ=,iv:YSlATgqJomXM7dM3D1Pg4mtNl9xW7z3a/jkxScsqvow=,tag:AbO4wP4C/uJsSC9UjsHZZQ==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:GnW+erepyzYMVIM8Bn5aWOM2jSKsvZWu6clHbdudtjF73MIk,iv:YTR+RnJdaPqRB4AfWPK9NB7b798wOMbjEyy9QWv36rs=,tag:cHapFnvDhFnD4kQxUbKqYQ==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:pWo9iAPxjKnsMFUo,iv:lx+nWYi/JVz8rDawjn9Fez4DpwPdNtWySUJGDvhhf7s=,tag:euGIbCLw/r7mRakuGeGT/Q==,type:str]
    prism_central_user: ENC[AES256_GCM,data:WBz0aPw=,iv:oPTIxVq9sy9zaYUXl5FGu+kLgHPPi7K3oeEPvfQjG7w=,tag:hxQRmtcJhgcTW1by8dG5RQ==,type:str]
    prism_central_password: ENC[AES256_GCM,data:NuXNaVPjI0mZ,iv:1/ovB7b/Z42u6BpzxOB5kCsNi/8cuwT0bi+XfdFJe9o=,tag:qJwJP67WuNNioSarwtBiGQ==,type:str]
    objects_host: ENC[AES256_GCM,data:T5mWrmQjMCNvnBOn,iv:83BK9XzdnO1N3SiTfcMJy5mvm33yauLTJaNrijUngIM=,tag:kmmzKXVDUJ3I3oh0a4uVDw==,type:str]
    objects_port: ENC[AES256_GCM,data:R5w=,iv:Qdft9dFayep6sW+0O7s9Z6FrPGaAyjRHQS520y68g3Q=,tag:ejpuc9LhsJMa/Rpg8MqlbQ==,type:str]
    objects_region: ENC[AES256_GCM,data:CylvedposcGy,iv:SLFz1GQesP4NitFd88wgeQzggggcY2VdtI3AQe0xgi0=,tag:lWDmlvMTkYAhR0cIT7VQpQ==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:nBiVh/8=,iv:4L6HfHdbrS3pjXunz2wZlHPUhbrEkX8n7TQEMRq1q4c=,tag:4hl1S+d8crjvY/3u4WKf/Q==,type:str]
    objects_access_key: ENC[AES256_GCM,data:6v+BDbmgB060wMbzlH40UiB1aW6rCvYkUUcS8+ohi+4=,iv:ZQsxOfxHSDubgO5OiGmmlY4jCfNlAltNZM34PcN6pnU=,tag:7ozUqY7Xg6u1l2gfsABjyA==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:OunD0S3AtjbpSaa0dELE+oG+5rQkWT/T1m+KPWSzY4w=,iv:fo3dkfzY/TSiay5nG554tgqb4GlrBJE9IZf5KhUZuWk=,tag:EU9itcREYgprB/uIqYS1sA==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:onO22f56fbbL/woM5uwEa8gfyaJp6ffUNA==,iv:OWix57mRti9R8y96gfLEcymqCRYevQgXgCx4LLM35zU=,tag:Z0zp2+tvc5epbxFd6DeK3g==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:VN7UAmQmWHte3aQ3CGib,iv:vfp22ked01frSW0ZWL3hP072oHVxXOIBD5CjKuvC31c=,tag:RZwqBDjfuR2e+dr3YqTMyw==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:udARjCvH/P6FbcZodJR3Eu813xTQE/3Pb+SW,iv:bXRwZSVfyYH9ahMfeHDYTkHjFBjLzm+V3bnQ4xosS3o=,tag:QhpUkuh/7Gf7MbpGtMDCYw==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:Dr1U2nh7yCuLbOKnwpkMQdNIT5hH5eM=,iv:r53APeOJe9lmo2c3QCAsZlhb5PsDv6nkX2SmOVni7lI=,tag:T0HiL1Y1/BHRf9BgnHF0kw==,type:str]
    kube_vip_istio_system_ipam: ENC[AES256_GCM,data:Efe4Ec1u3BU9Bvk2nNiX,iv:1JXmqXMt1kIb39zEiAFFdld8l3ROtiHCQya7BO2/9vY=,tag:sfMLGyO6D2C3+J9cxhdgDg==,type:str]
    istio_wildcard_ingress_subdomain: ENC[AES256_GCM,data:HOWp9Q6YoqKkjl+/YuteE0F9rZI0GHRvIo/4Kqn4tQ==,iv:93AV2wknSRSSQGWwZGx/7+paCAxGKluVzbosrYUQmcI=,tag:LkAcd1cJ6nWbkO4x9Em7Cg==,type:str]
    huggingFaceToken: ENC[AES256_GCM,data:odb0x2Y+ijlnpf375jRtFPEGGENmAg4y3g8B62zc9IyDv4mdTg==,iv:Fbud5rwiBZeBucR0NQRnwMsLgXwsc2kPGF8IJq05nOo=,tag:uvk9hjS6/VmY7BNTRnaOmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17m5tuavf9aam25cdguwmv3qfywyt9wclvwwfvqaeads02t4py3cqxfz686
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCYllhMmlQR09MRmJrQXpx
            OXUvMXlxYzhmclNMRWJSYk1EMEw2c3V2U1I4CkFCMFpVZ0NXTmdSTnczQjFVVmhv
            N001cGNKaHpsZCtURGlEWXJpNzRhMW8KLS0tIDNQdU5Rck0vVVcwVjdWUFJpa1lv
            OG80UGY2RE1vZkpua3c3NnR6Y3kxMkkKThmXi8QvbWJeHWy8UQ0TUFBKplhRdAGH
            JK249GE2pJWjv+flFmAYDoQfo5leWzHOCjYcfsoAqd/l42zZKoJOsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-06T03:17:20Z"
    mac: ENC[AES256_GCM,data:folUkNW3VRBZWPPjR3hgYmz8/e2VXuD2yLPQ03kvgkQ9wCBhq3afVJZFBPhP8lCXPPF76cMYqa2mWb8OV7Pwle388y/Q3D1Ky8uOHh0b1x8zEDstyaS7x/x3E20cApc6QXKUhfJxCuCWq5na+L0wpOqdg5y8xl4gY+1GCIpySQ8=,iv:alSsJeZ6T91wst9sigWx2EUvm10k52LeYPju0NrHPvU=,tag:F1+rKyMSNtae8BpPtqg7QA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
