kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:8IKjEvJ/iFxavsRYN/tL5oZpQfuNjfUCK5Cl4ZuyvEgnPxXfKm64SoFtDxqe,iv:X2X88T0YUe6smaZb6SbMCfflMnKiXAOKyTamJKOhVTQ=,tag:UNUHfZLPtl77abHNZdFvSQ==,type:str]
    github_user: ENC[AES256_GCM,data:KGpMqv38,iv:X7OFzXb/jf8dN1IwMDg27TBAHxEzQ+AlIKfa90Ll2RQ=,tag:ZwRNM2aAkMX/GIlbH3U21Q==,type:str]
    github_api_token: ENC[AES256_GCM,data:Knr4C7T7C8wGLbNHqCp823YhCeu41QNXF5T3EB+6klFhvbCX6qkbeQ==,iv:Yz10naSFrH2a4qjB5WSjs3alaHDRmTfZmNvL0iQfHxM=,tag:u0qRvgQ7L6cqbdxaEmbRYQ==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:WzuS8gZT2Zg=,iv:T+408IhPcyzV03BBIk0PC5DXoUvHJp8wyyCnoEdEPcw=,tag:E+PEHwOIdRIjJIxKcOmw8w==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:G3iaqHepOhXTamCkv9BZkexPcjxRWp1gKvDLsK3WWEF6F5j1,iv:FTiXK1UjNt0pwdL/II3erH4xJhWBiqrOGZqV2ykZIpU=,tag:r+BCa8ozGoRx2AWXcBZg+A==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:sGaDDS3Lk5/USzx+,iv:RilvlG39bgm7GibQmNztXCQgA9PdtUgLJPCp5ARo9uE=,tag:ThS6d8ue4lxi50jEDfmX5g==,type:str]
    prism_central_user: ENC[AES256_GCM,data:Rh8ovgk=,iv:yz+k6R3RG+2Y7fCuGGIRAeBwbbueJU2iIOPnYuekt/8=,tag:d+hPULmhwcuY0fJLdH4HVg==,type:str]
    prism_central_password: ENC[AES256_GCM,data:cydmdf/SZFK+,iv:3MGFCIjbj8yJogStzOAhqOKNyH1nAgQ7qXcjFh/tUR0=,tag:0lmd+CKDSfVRYA0nGl0pYw==,type:str]
    objects_host: ENC[AES256_GCM,data:rIuCAzMFzaPq/2ge,iv:zluhUoVRfvCP148+0vWZcDnvmkhMhnCecw9qyTziquc=,tag:kcw/tkphr3CmbhG4q4cZgw==,type:str]
    objects_port: ENC[AES256_GCM,data:ngk=,iv:uy2pfKZ/gM2vObX/0dUl79ozqxtm66eU7pvmIHA2mV4=,tag:kWc6mbhAzwGhkDDBnkfbUQ==,type:str]
    objects_region: ENC[AES256_GCM,data:QqQ94+9mJOGl,iv:npw4mhy9rAmooodrgPwUQlDP07Z5Dn1a5cGcsy+rLnQ=,tag:2fIajyg8xzeHKKtChYNFqw==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:e42MiSg=,iv:gZ2AtgO1KBo0jbqy9jlAhVAgMtZr7zcvN7fHh//LX2I=,tag:Vwc4yHxQFztXxmZovBlZKQ==,type:str]
    objects_access_key: ENC[AES256_GCM,data:BFjWsTTcxWXRx7KMWXOp8X4dJkzHZi2uWUEqW7cwJH0=,iv:Q5ehEUqyQtuhA1Yv10kZh9REAidZBCQrjqIfRzpxjBc=,tag:kJX7Qiz0gZX6uur5f8xAbA==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:ATkDw+1ZoMzoO17a0H5o6H10m3i8CALGHZSjiZi3eYQ=,iv:CPbwAkp/EYr9t/NtuPHsYR2hMzv8WFrwbvMoXAKId4A=,tag:tHwVfiUFlErl1lxu6iyjhQ==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:94uzjzQLs7phmg3u1xNaAuYSMN7KgyNDpQ==,iv:MAMo9Xb9DRTvwWBQkg2zlQedjOnClrQbHzGdJLLEMjk=,tag:QSJR9H1G1FBaIsLLGitflw==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:cTD7fCXPuhRtbbvHmn7U,iv:tpjBperm5fy1aq05ovj9mDn7Wx5wCkIMIUopoCLm2LI=,tag:X45Yazy6cni5JSHWGKXJfw==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:uVv3qx/M259nE71YvvBK0zm4FM94wTqvDLcF,iv:FpyKX+OJhEgtFhTB94lQVwmIkqydnOEkV8nQSRa8H0Y=,tag:WdbCoX5okYgXgCNR9Curxg==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:DvZrlAXIpdglNR6Cr8Ud78je3yiM48g=,iv:x/dlxfawMeoYIzM11UECfyCeE6AwgMonww1ldQ8PEh0=,tag:ddGMFyVglBRizexMkYMheA==,type:str]
    kube_vip_istio_system_ipam: ENC[AES256_GCM,data:3rBxbNsrXcAbIK6wT7Q4,iv:AL3rG5um7qh8ryxEp500I4Bvjl4/cuKxLP0uVn6iymg=,tag:egCXdsRO1QCwX8FNcMPgYw==,type:str]
    istio_wildcard_ingress_subdomain: ENC[AES256_GCM,data:rKqfPjvsvufepeDyBETs3AIF8mdgMOJp+fUAsNLyag==,iv:9+nPr9JijbatwAqJbsmTr1gle2MNv4GWl8xmUv3GPlc=,tag:F25TqQ0Moum8K7aQXE7JEw==,type:str]
    huggingFaceToken: ENC[AES256_GCM,data:FeOQ6lfGzezq6cEbd5lu/93Wck0nqAsZMKA0G4MGHI1Mmm0c8Q==,iv:IJ17PhuDyQaqGiI8182S8lFCBmN2sGMi54CVXD1JrE4=,tag:5fSlfKKZNQXFo+Ux3AKjYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17m5tuavf9aam25cdguwmv3qfywyt9wclvwwfvqaeads02t4py3cqxfz686
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYb295cnBLQzA0Tk9RdXZk
            M3FpeS9TWldRR21iQ3BYaU1vYWdaUW9qU2hJCmZ3YWJrdTBQZGd2V205amR5R1Rk
            NkF2RTRCVTU3WWlpZ2pvcGZzS2oxWk0KLS0tIElneTRaTHkrV05kRmh5N3dSUDZW
            UkJ5SUlPMXQwSmRvRkkvcGRDRy9tZkUKr25coCLJvRZAOwlY9mfqGKqylbvBHXpX
            5lH593TpcUroEmpS7w/PWRGh6T1/YxQeFJ69ovX70zn5H/3BZJ1sKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-15T22:03:43Z"
    mac: ENC[AES256_GCM,data:E350fMbJuE0eGdE/eByEv32gxUYf623nuNrQJlL18D6B+Z1XNev5tPnpty5j/5ZrIsQ8ooQgwBglsKachYZJmpKwWO1gH5SOW0mJUSVJ6bbsXAhGtCsNNqUKeDlK2X4aZ+UKWUDbKedkIo1yrpN932MvzcaKA4Xljn1eEZa7mDo=,iv:ukaylrh8f/0nXxpRQBki1TQ7iTdjS9BpMbOGL2g2ccM=,tag:gQXYblG0FHBmhtht0RcVOg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
