kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:ZyYniJARCixymHKxGzesWKKxBUc/vriyhVutWppaNhA6moFs+FKSYeTtKX+6,iv:U2PwkQW4T/nxYrJ+56h+ZrLfMZm0L4b9JWkCy3TDW8Q=,tag:DIjP1xSXnp+114EoEVBqdw==,type:str]
    github_user: ENC[AES256_GCM,data:p/wO5pHm,iv:kYMG6BxEdX2Q6qbIH5cKSU3b0ARrjtqNZunjiB4+9BM=,tag:9jexUqPkKp19MtJyUuR//Q==,type:str]
    github_api_token: ENC[AES256_GCM,data:V0NUTk+dE64lre9K7yELMySEKGEEgajPzo6u6otPpodqkDbLFNnRqg==,iv:XpjroSWMn8ZIxd6fB+Zqqjta8yQs0goLbz1pT5rGE+0=,tag:9TMOsiI8zumEUh+kZlGFgw==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:SHwjouQPcAY=,iv:IGeRPsGt1dLjs++SmJXyt5OcN4eeke+sNGfUVUy6ev0=,tag:3X2wU2ajaMFqV1qBv3B5kA==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:q4HAd/MVjkVbUzefH65xS0DhplhDn8Z3mmi534wN0RKNbSP0,iv:/1fMb0f5kucN0ROmZDIpzE/2bQwgTt5wYYpCBTg072o=,tag:DgYxTLumIbiv6igl94/BWw==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:341j6CbDdN1y86W5,iv:aIxSKbEZtMf5+T2/jjf6DAFxSLDzXWrobcd8BtTZZhI=,tag:Dd+MmZwWJI+TZ5uibRJhQQ==,type:str]
    prism_central_user: ENC[AES256_GCM,data:salSQCw=,iv:GBHziSa/j23Huj5afff8Bw4hHyPCiHngvvvKezDJZRk=,tag:XWYjbuCITaiE3SxfyF+pcg==,type:str]
    prism_central_password: ENC[AES256_GCM,data:IUMqwjRcu6DM,iv:fm4iO+vNtoYXWq71q1iHBZwTnXc8L5TY037vyDGvvxg=,tag:bU8smcl3cwhosTVZfr7iFQ==,type:str]
    objects_host: ENC[AES256_GCM,data:Jirstpl9KVhvufeX,iv:7JraYIjcKZcq+hmcoG03CtrGoilrZpJdth+hadgXivs=,tag:PrXo7eV+HJR0Sv7dw75KKQ==,type:str]
    objects_port: ENC[AES256_GCM,data:YQk=,iv:NWkQRljSdEwn8TaHEoo0YN8n7430qB6Wjft9W6u1EKY=,tag:6doDrHuorSwRH4JeFFrAgg==,type:str]
    objects_region: ENC[AES256_GCM,data:lLX79xFCQbXQ,iv:tQjZU1FFhRqG7+uYmasdG6xr3Gy4RAFI/uyfQTQ6xOk=,tag:hvz+XnIpnNbRTpNfhQni2A==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:nYsqhnY=,iv:42HrsfXoWjJAsrnEw+q3rN5W8NOQpldakbHPPHbmPaM=,tag:7O98nORdGeIW7t9aGh7bmw==,type:str]
    objects_access_key: ENC[AES256_GCM,data:WCGcTDS+oSV/vWjt/EMeBRXlCUG3twRiEFO2Yhw6A+Q=,iv:Z6janxAolZP73zi7F1Tr37cz/6kFUDin1PEs4YtmxLA=,tag:arJpw5zTJtRoa4FhH6Pvnw==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:Rnk06affBFFU8kOo2s/vjsCdPYG/IVns96N2Cihd+VQ=,iv:oW6Ypkj2uW+te0rxRWZLi4MUSqnpX/YfDRD2NMnGP7o=,tag:wT6T5irRryez7RRmH8jepA==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:bkQ6WteiFfsYS/0Qctj2Q2O+ZCwUb1Pg4A==,iv:4yIy0796WdrhiB3ZdNNqipbMvequGLwNDLhH5BNtZn4=,tag:fiVE4NQ8l5LymcBtUJNuxQ==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:y1b+tIOuOQKy6/QrcmPj,iv:EbougQPg0jt/diHd1V61DQHDNsDhqwg8Xj2/aoXsBIg=,tag:PGMSbXAvdTMk5oVgnJBUhw==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:hFJfOQ3g+QQ4UeZ+i5tb5lqosqr/KqyVKzFk,iv:lRuHa/kQNxsqT3LCTrvEE9qEiMZzijdoFmMVJd2Pz/U=,tag:HlSp3ZizpHjkDCV7ysA5YQ==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:y7IrFazYqSY9x6mDiFx4Fh+imy5AlK4=,iv:oN6qwRfW8bPJv9c0vLxGDlxd8iSNYEPpU0NW1M14/hE=,tag:uHs5TLJeNDfuurG59cehUQ==,type:str]
    kube_vip_istio_system_ipam: ENC[AES256_GCM,data:T5aV4DgUH3RzxN2yYM0o,iv:DuuwRTi/4nVd40fTBygjPK9qDuixq86FQOpBTU4stIE=,tag:lK/wpu0TGbMH6QhEX3J9Jw==,type:str]
    istio_wildcard_ingress_subdomain: ENC[AES256_GCM,data:3uETIbEFAzXTn09Sx64FPqYsEacVDFrJnjG5izXXTg==,iv:82F9edrsF5TEw/wUG+BXhQec29cH1VQDEYjr/q/At34=,tag:T/S/3L++8SwmcFHJYnn8zQ==,type:str]
    huggingFaceToken: ENC[AES256_GCM,data:xSgGuMZy6Vs0YH+QQURsWshYozrdTKj+BiwFvDLuxYMeYYWrxA==,iv:EzZJHCRuxDjse09Bah+1j0Gv+3+Y4AIfR1xzPYlAQoo=,tag:KciAR7MYCflT8LnzmZlanQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17m5tuavf9aam25cdguwmv3qfywyt9wclvwwfvqaeads02t4py3cqxfz686
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUUxSWkRDUU8ySlZpbjFO
            ZVAvRVA4Z292SXBxT3dkZGhZaVZJTW9RR0M0CktQbVArWUk0L1BlMnh2RE9nUE1m
            azJqTjhIa1NSYnhQNmtjYzk0Q3grbFUKLS0tIHZ4WVpLQnBqZjloSkZqZ3JkdlVr
            QkZINWtnVjd2VVpKdHVJSmdQRG9od2MKHUtg6IYbYyUEVpVx5BnQsyFMZ9wLJHN1
            j+PApLbcl12MstBeRUgdzPO0gNEABMzwtzg80o709iNgGF+pgqt4mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-10T20:30:02Z"
    mac: ENC[AES256_GCM,data:L3racPIX1WUXkUv+2Seq9qCM1eOBv7KDkSUakU9llyzpzUFe/cZ88hK3FTNZyyN5nMZ62jASurp0UoHLVC24nM6+EWVDuTyoBck0gIjr8gUwpe3sKYBHgWIQ5lAKLcIotrCFPTa0ej2XRHkRjilFg93rT2G0TwRJvYXYZ3rLgC4=,iv:oze0N+cxKPkNvAM2Ff2xBt+Fvys8hnKwbgOnLqgLq48=,tag:9x1J9UpCwGZxwzH10qk+dQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
