apiVersion: v1
kind: Namespace
metadata:
  name: weave-gitops
  labels:
    toolkit.fluxcd.io/tenant: platform-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  type: oci
  interval: 4h
  url: oci://ghcr.io/weaveworks/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  targetNamespace: ${namespace_name:=weave-gitops}
  chart:
    spec:
      chart: weave-gitops
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
      version: ${weave_gitops_version}
  interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
    preserveValues: true
  # https://github.com/weaveworks/weave-gitops/blob/main/charts/gitops-server/values.yaml
  values:
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 1
        memory: 512Mi
    securityContext:
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
    adminUser:
      create: true
      username: admin
      # Change password by leveraging bcrypt hash generator
      passwordHash: ${weave_gitops_default_pass}
