kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:ASzntrcn/epCq+kBFjfqEeWuoRbpzQvsBDcPTHYsA6one1ZR+seOCuZRqyJ4B+JhJKN9/yTKR5J9,iv:yLSQBNZDE/MH46hXxpO8h/73d+ajFxPFlUZh3GkRNE8=,tag:xCrN1+1YFxzKf239sLocAw==,type:str]
    github_user: ENC[AES256_GCM,data:hTlYAKSjD1SMMzJIJyQ=,iv:dDc2IanM18UhuRhO9nSHWfvgwt4SI65gw4R7sdT1yH4=,tag:CHNXWACkFymiiIb02cRbYw==,type:str]
    github_api_token: ENC[AES256_GCM,data:3sc/xbCzaNZd77lryZLqzIgp+ME6dqsnWEl1tZqUH099QeU8yfVabA==,iv:cIF4hhQCFY+jKFcUOZIkOyQIj/85KUc3k9nEExR/R7E=,tag:z5vYYigKdSn1bZrgblFq5w==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:bP9Q0tgfMHomfXbb,iv:F13t72DV6lCWLQfRNS0rWNBaUj5gk3iei2KhU1ABK7g=,tag:5EVSvo6GCUYC2x886sLgsA==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:nD2dLXpcNtRJiu5ua6Qz,iv:8uEugoEYN59zcxVOvC8bJmPsvJQCbjihivG1SjV111w=,tag:HULUUlbi46ENnvs77XUmBw==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:/81fcT8hQniNXmeAZOjTmyoSzoIomaOtMG7sknwundo=,iv:P8i5ym9XnzjLBbhQlk15pVLAMeJrZD2Ow+76kT2PTv8=,tag:PqV14AN+YMg898Vra915Vg==,type:str]
    prism_central_user: ENC[AES256_GCM,data:JMwVWFg=,iv:mrlOxqM3q5uyVAC8NVL7RXgd5f6f3kRXc6qoDYyLj7U=,tag:/I0h+aFPJz36H8H01wDg0Q==,type:str]
    prism_central_password: ENC[AES256_GCM,data:FQGYAJS+eaf3PS4=,iv:Xr2G3gx0LQ4k8b4dFBfhIxkM7N0Lxwlgl0iI3EqNnOo=,tag:t3D/XXuYgf6StiuwYQVyNg==,type:str]
    objects_host: ENC[AES256_GCM,data:3ewmQJfxsnG6TlPusri3Tc84ylXYsXcuY0alHESSMOjYbRNYGA==,iv:tvDjlGlVKxRQHp0/XYOBZ7TpspUZzEtZAueADHKxibc=,tag:+R1lPHTqbOkr9JH00gkIPA==,type:str]
    objects_port: ENC[AES256_GCM,data:NN4=,iv:EYLMgOuR0BaNPK2bSC6DcudNqcA3a4sLDWiLZiP139c=,tag:QNdM0recM6ZhlMjxD6yo0g==,type:str]
    objects_region: ENC[AES256_GCM,data:n2I9hKG91tnY,iv:RxsemXkw1p8Nr91Rv1d+a8scIpbAI3+aOUvaiP4hG70=,tag:TNJTUl7IAw6CGcuuTkfwCg==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:Rk/fzvQ=,iv:pXPeNwfq14jvlT3EbMILeChagCfTutyI826stZd48Sk=,tag:78HKpsflpysI1oEJQcUwTA==,type:str]
    objects_access_key: ENC[AES256_GCM,data:gUl0lmWc+vaPUGrNHfFFR16LTQJ+pVI5SBmscmxnAtc=,iv:wdFyLHahrT15G7UnVfH7+Sv6ZgPxrsDrv7Lht0ugAKI=,tag:/pnvntkW2XnB++oqvxQTHg==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:vwZP7CmSCf/KVlirLjE/8NfkI9vUfMazcGCnDg2f700=,iv:gzdaZVMGtKRASPo7HgeVyVJ10AqMI5a3WuFHJQofOLY=,tag:NVv7Yap1C4u5UmRnCPkmnQ==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:1D8/wOmS7BUgoVosLP7PybnvJQvW3dE=,iv:BW9d2RUtXSty/JWUF4/4HR20ksa9/YD6a26U8V8obVY=,tag:bNv145PeM4S0ZH4QsrMPBA==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:IumrPTJlEmbgxL9ieew=,iv:ij9tP4ZSGTIc1TecdxwabWxzD+e2XwBBHsFey/FAbbk=,tag:0FbsPevuofk5d6RJF+jZjA==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:WV8FoKzCwcZFHDpFcjmAq+HOZIBso7NC+84Fak3c8jduaS0+O0SL,iv:kwPl78kecDHx0dhUogBMxaUd4E6cgTla5H/7GL4yjZo=,tag:cJyduTru9znWI+2As1etqg==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:224SVcgCmIf8D0XfK462dWDt5StKy6kaFAONaKsaC3Z9AyBfWkDJOQ==,iv:3IxZGM5GSQrRlaAhgiihQH7qCEz+UrovhfyVjXtQFvo=,tag:8+GJGO57L8K9iVFZFM69JA==,type:str]
    kube_vip_istio_system_ipam: ENC[AES256_GCM,data:WE7vDnlnHrgMX/NrIYQ=,iv:fFjMbcUH3Gc/Oo/32ZufS6VjJV0Fz3LorZTLiQgFk1E=,tag:J5i7nKcrckSHNW3dbECaDg==,type:str]
    istio_vip: ENC[AES256_GCM,data:I69SeXi3dEg+qPI=,iv:C7oj4yFUa0wFIL/xLJqDiRlt3DbzyLE+NND28GgegOI=,tag:MYeG+/+qNZWWVtrk7lqZiw==,type:str]
    istio_wildcard_ingress_subdomain: ENC[AES256_GCM,data:4ZUOnS94NTkvsWNhuDDut80gtm34lgWH54vWBwKd/9w6t5K6QgKZ,iv:1ZyS9IuFw+CB1Mcuaq8KrlzlTWrsSjPngk3Ov6Uas+k=,tag:qv2XN/myJ9j5w2n28MzC1g==,type:str]
    aws_route53_email: ENC[AES256_GCM,data:etUUE9u4WmEKX+WqA6ofXAWNw1AY5tcXizQ=,iv:ZI64SQpPGH2fVR/eOvWUNGYzH8eOcU5LyDov7CFz6w8=,tag:pQkTUaSrXKQ7Ui0k7Limjg==,type:str]
    aws_route53_dns_zone: ENC[AES256_GCM,data:nEUCelVQr0S1kUXvMcwh5+WMiqXptw==,iv:rqOjuXjIKiPpYm57KLx8m4EblDj9C5DLfDP/0VXq7yM=,tag:0t/YA1pMJc/WwcCP9n7k8w==,type:str]
    aws_route53_region: ENC[AES256_GCM,data:DWHg3x6sGdOc,iv:mUGfBoiaR7tIC6b1VSe+RFWoGLZ/X68pLK9QFm414bY=,tag:Augmb6oqRkN3/ehSxSm54g==,type:str]
    aws_route53_hosted_zone_id: ENC[AES256_GCM,data:1mGnOtpY0RJzldmybojqkYj1IGhf,iv:oL9tbnPTIgj18Fy7GVHPMLoU+Jtxh0KzGPx1C1si8+k=,tag:icHZj9UvRdzmh7Cr7WtQ+Q==,type:str]
    aws_route53_key_id: ENC[AES256_GCM,data:MRKTiLrxb0ttIb/iAYK2XfXlghI=,iv:wHGkS3bDRLGGsbFQXMZdbRFXmopKL7jnbG7SV7As6Nw=,tag:eVCHUsfiFFCe52eDKkf2wA==,type:str]
    aws_route53_key_secret: ENC[AES256_GCM,data:ORqci+T2bbY2CSHmnYZvAIolYO3eCD7nghBwetczVgAJBhqa5gU0XA==,iv:CHhbl/YcMeD6jujtEvmooSR3Yo0SSaXtKQt6PU5bVHw=,tag:WyTfjYLTphzCyz+BRQIIYw==,type:str]
    jupyterhub_default_pass: ENC[AES256_GCM,data:R/8Tu7I1KicdqJfKl8VyCQ==,iv:4jXlZkC4tslrE9r6NU2mGXYzMov4OT8e01lkLKrZx3k=,tag:eupStJV5Q+z1FSBeGEmwpA==,type:str]
    weave_gitops_default_pass: ENC[AES256_GCM,data:XfQfvG6jmQaRoPIIdvpis2i6vAKbwpYZzhH4e2ZURgLznIonHmw9jy4o+8X7bZ3qQkkxBLQuuG3icUg6,iv:BI3hDLV9zFYxEOO7JJw/P9Qhvhk5k670EcXkPgjlKqM=,tag:8i+cg1hXK4xnQaAwtdE2kA==,type:str]
    nfs_export: ENC[AES256_GCM,data:PAr7XSi9+n8MyUY4azuZPQ==,iv:lx1h+fvgO+AGWTKNyj/YF5Jm4DU+zHlFiWKT17kiJXw=,tag:GcbAysWUE1e2LG16qW6NnQ==,type:str]
    nfs_server: ENC[AES256_GCM,data:5CYrg9L589TDxqcj2SbljhNNkYiG903FY54FY9Prw4prqZc=,iv:SBPgDddRuK8QLkoyA6jYqRYqR5VozjAt1fqoOpqZkYw=,tag:7mrN2pNMWjvUgf8t/4Wzpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUSs5SDczL0ZTelBtTU01
            ckJPSzZnSHFvRmJWMGpDT0F2eXV0WVp3Umt3CkN0ZEhxcmN3dXRNWVBpODVINGRT
            b0Y0YWxvaENmZ2FMeE5ySGYzL1JtWWcKLS0tIEducUgzbGhwbmFabXV1enpOaXU0
            THlYSUIycFR5dmltc1lYd2hXNmtIZDQKK57h4fxQ4LZeoX2tWa+Z4Q++VjRZQy3k
            WmFKTU6Gl+q2dGjXyDR38ye28KDFLQ4v6SnxFC24HUI3CiwqMSZX7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-25T01:27:44Z"
    mac: ENC[AES256_GCM,data:fC41jekpJGb7gM6cpfmboHKdb/K5H7YP1mcpWE7NNSxlC1ETCXmxSCPcjLCnwFjD9zrldPsgIl+FlLioa0C35KDIBzJbHir/VoolQncta4wdBGwUmXwMF3scHPDUgcn7FJnqz0p6xVHwxke3ps8STOrVaXo6RYwtthggqfd08Xc=,iv:MrCDLUQz4wASeReJZo6KnNPIx/UXHdQd7V3rqbNhbhk=,tag:L84HttKzjHaaFYKxFsDdyA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
